set shell := ["zsh", "-uc"]

rebuild:
    sudo nixos-rebuild switch --flake .#titan

submodules:
    git submodule update --init --recursive

gc:
    sudo nix-collect-garbage -d && nix-collect-garbage -d

setup:
    rm -f ./cfg/hardware-configuration.nix
    sudo nixos-generate-config
    sudo mv /etc/nixos/hardware-configuration.nix ~/config/cfg/
    sudo chown tyler:users ./cfg/hardware-configuration.nix
    # so that the rebuild acknowledges the file
    git add ./cfg/hardware-configuration.nix

    just rebuild
    just setup-gtnh

    sudo systemctl start gtnh-mc.service

